file: fetch_x_profiles.log
sample_limit: -1
chunk_size: 100
load_to_db: true
store_csv: false
tweets_sample_limit: -1    # -1 => all, or set e.g. 200
sample_seed: 42
tweets_since: "2025-09-01"
id_cols:
  - author_id
  - in_reply_to_user_id
count_cols:
  - like_count
  - reply_count
  - retweet_count
  - quote_count
  - bookmark_count
  - impression_count
skip_fetch_date: "2025-09-28"
year: 2025
month: 10
outdir: output
top_n: 10
tweet_fields:
  - created_at
  - lang
  - public_metrics
  - conversation_id
  - in_reply_to_user_id
  - possibly_sensitive
  - source
  - entities
  - referenced_tweets
rate_limit_fallback_sleep: 901
trends_woeid: 23424829
trends_place_name: "Germany"
# existing parameters...
ssh_host: 145.223.101.94
ssh_user: app
ssh_port: 22
ssh_identity_file: "C:/Users/felix/.ssh/id_ed25519"

remote_base_dir: "/home/app/apps/xminer/output"
export_patterns:
  - "202510/profiles"
  - "202510/tweets"
  # - "202509/trends"
local_dest_dir: "C:/Users/felix/Documents/xminer/outputs"
